spring:
  application:
    name: interview

  # datasource:
  #   url: jdbc:postgresql://localhost:5432/email
  #   username: Joydeep122
  #   password: Joydeep122  
  #   driver-class-name: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: update

  

server:
  port: 3000
